language: java
services:
  - mysql

install: true

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x pandamonium-theorem-prover/gradlew

before_script:
  - mysql -u root -e 'CREATE DATABASE pandamonium;'
  - mysql -u root pandamonium < pandamonium-theorem-prover/persistence/sql/local_development.sql

stages:
  - name: load database
  - name: build
  - name: unit Test
  - name: integration Test

jobs:
  include:
    - stage: load database
      script: ./pandamonium-theorem-prover/gradlew loaddb
    - stage: build
      script: ./pandamonium-theorem-prover/gradlew build
    - stage: unit Test
      script: ./pandamonium-theorem-prover/gradlew test
    - stage: integration Test
      script: ./pandamonium-theorem-prover/gradlew integrationTest
