language: java
services:
  - mysql

install: true

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x pandamonium-theorem-prover/gradlew

before_script:
  - mysql -u root -e 'CREATE DATABASE pandamonium;'
  - mysql -u root pandamonium < pandamonium-theorem-prover/persistence/sql/local_development.sql

stages:
  - name: build
  - name: unitTest
  - name: integrationTest

jobs:
  include:
    - stage: build
      script: ./pandamonium-theorem-prover/gradlew build
    - stage: unitTest
      script: ./pandamonium-theorem-prover/gradlew test
    - stage: integrationTest
      script: ./pandamonium-theorem-prover/gradlew integrationTest
