language: java
install: true

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x pandamonium-theorem-prover/gradlew
  - cd pandamonium-theorem-prover

stages:
  - name: build
  - name: unit tests
  - name: integration tests

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: unit tests
      script: ./gradlew test
    - stage: integration tests
      script: ./gradlew integrationTest
