language: java
install: true

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

stages:
  - name: build
  - name: unitTest
  - name: integrationTest

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: unitTest
      script: ./gradlew test
    - stage: integrationTest
      script: ./gradlew integrationTest
